name: 'Lint Action'
description: 'Runs clang-format'
runs:
  using: ubuntu-18.04
  steps:
    - uses: actions/checkout@v3
    - name: Install clang-format
      shell: bash
      run: |
        sudo tee /etc/apt/sources.list.d/llvm.list >/dev/null <<EOF
        deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${CLANG_VERSION} main
        deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${CLANG_VERSION} main
        EOF
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add
        sudo apt-get update
        sudo apt-get install clang-format-${CLANG_VERSION}
    - name: Format src/ripple
      shell: bash
      run: find src test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format-${CLANG_VERSION} -i
    - name: Check for differences
      id: assert
      shell: bash
      run: |
        set -o pipefail
        git diff --exit-code | tee "clang-format.patch"
