# action.yml
name: 'Linter World'
description: 'Run a clang-format'
runs:
  using: "composite"
  steps:
    - run: |
        echo "yo"
        ls -lh
        find src test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format-11 -i

      shell: bash

    - name: Check for differences
      id: assert
      shell: bash
      run: |
        set -o pipefail
        git diff --color --exit-code | tee "clang-format.patch"

    - run: script.sh
      shell: bash