outputs:
  patch_file: 
    description: 'The correction to apply'
runs:
  using: "composite"
  steps:
    - run: |
        find src unittests -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format-11 -i
      shell: bash

    - name: Check for differences
      id: assert
      shell: bash
      run: |
        git diff --color --exit-code | tee "clang-format.patch"

    - run: script.sh
      shell: bash

    - run: exit 1
      shell: bash